### ISSUE TITLE
As a developer I need a way to pass Twilio secret keys into server side code without exposing publicly so I can securely integrate with Twilio services.

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/infestation#11]

**Comment by bryankennedy** [comment]
I forgot to get back to your message on Slack.

I've done this by storing the key in a .env file for each of the packages that need access then you can read the env var into the application using the [npm module dotenv](https://www.npmjs.com/package/dotenv).

Here's an example:
https://github.com/scimusmn/user-management/blob/develop/clientApp/env.example
As part of the install process you'd rename that file `.env` and add your secrets. That file doesn't get tracked in Git.

Here's an example of how you'd read that value into your code in the application:
https://github.com/scimusmn/user-management/blob/80e4005e8aeeb8a47d4ebee05c2bbb77a852f207/clientApp/src/Auth/Auth.js#L13

**Comment by tnordberg** [comment]
Thanks, @bryankennedy, exactly what I needed.

**Comment by bryankennedy** [comment]
@tnordberg do you think that this is ready to close? Let me know if there was something else you needed to do here.
