### ISSUE TITLE
Add `room` seed data

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/infestation#20]
@tnordberg can you fill out the room data in the [game-2 rooms seeder](https://github.com/scimusmn/infestation/blob/master/packages/server/src/db/seeders/20190319214738-game-2.js)?

**Comment by tnordberg** [comment]
Closing after commit:
https://github.com/scimusmn/infestation/commit/81d060f4c07bf7edbd503af73a5c7f2ee29704d4
