### ISSUE TITLE
Restart Variation game with reset button press and on timeout

### ISSUE THREAD

**Issue by bryankennedy** [scimusmn/infestation#32]
@tnordberg commented on [Tue Sep 18 2018](https://github.com/scimusmn/tg-inheritance-game/issues/9)

---

@bryankennedy commented on [Thu Feb 14 2019](https://github.com/scimusmn/tg-inheritance-game/issues/9#issuecomment-463777445)

Manuel, Trygve says you're working on this. Let me know if not and I'll reassign.

---

@bryankennedy commented on [Wed Mar 20 2019](https://github.com/scimusmn/tg-inheritance-game/issues/9#issuecomment-475098111)

Is this still active?

---

@calym commented on [Thu Mar 21 2019](https://github.com/scimusmn/tg-inheritance-game/issues/9#issuecomment-475384246)

Yeah, this still needs to be done.

---

@tnordberg commented on [Thu Mar 21 2019](https://github.com/scimusmn/tg-inheritance-game/issues/9#issuecomment-475391060)

Removing myself from this task. Caly is on it.

**Comment by bryankennedy** [comment]
Moved from old repo and clarified scope.

**Comment by calym** [comment]
I found a pretty lightweight npm package that does a timeout on idle. Any thoughts about how long it should be?

**Comment by bryankennedy** [comment]
Let's start with...180 seconds. Easy to update as we find out what works in the exhibit.
