### ISSUE TITLE
Track score during game for each user

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/infestation#8]

**Comment by bryankennedy** [comment]
Good catch Manuel. I just transferred this to that repo, where you're working on it.

**Comment by azuldev1** [comment]
Just to clarify I'm working on this within the context of the inheritance game only. Not the overall scoring or progress mechanism of the Theatrical gaming experience.

**Comment by bryankennedy** [comment]
Closing this since it's tracked by some other aspects of the user database system.
